--TÊN SV:
--1. TẠO CSDL
CREATE DATABASE QLBH
ON PRIMARY
	(NAME ='QLSV_DATA',
	FILENAME= 'T:\DL\QLBH_DATA.MDF',
	SIZE=10,
	MAXSIZE =20,
	FILEGROWTH=1)
LOG ON
	(NAME ='QLSV_LOG',
	FILENAME= 'T:\DL\QLBH_LOG.LDF',
	SIZE=5,
	MAXSIZE =10,
	FILEGROWTH=1)
--2. MỞ CSDL 
	USE QLBH
--3. TẠO TABLE
CREATE TABLE Sanpham 
( Masp CHAR(5), 
  Tensp NVARCHAR(15), Dvt NVARCHAR(10), Dongia SMALLMONEY, SlTon INT ) 
--4.Tạo cột có giá trị phát sinh tự động
CREATE TABLE NhaCungCap
	(MaNCC int Identity NOT NULL Primary key, TenNCC VarChar(25)) 

--
CREATE TABLE NhaCungCap1
	(MaNCC int Identity NOT NULL Primary key, TenNCC VarChar(25)) 
--5.Cột tính toán - Computed column
CREATE TABLE cthoadon
( 		sohd int NOT NULL,
		MaHang char(5) NOT NULL,
		SoLuong int NOT NULL,
		DonGia money,
		ThanhTien AS SoLuong*DonGia
)--SUA CAU TRUC TABLE
--6 THÊM CỘT
ALTER TABLE NHACUNGCAP1
	ADD DIACHI NVARCHAR(10)
--XEM DL
SELECT * FROM NhaCungCap1
ALTER TABLE NHACUNGCAP1 ADD SDT INT
--7. SỬA CHỮA KIỂU DỮ LIỆU
ALTER TABLE NHACUNGCAP1
	ALTER COLUMN DIACHI NVARCHAR(60)
ALTER TABLE NHACUNGCAP1 ADD SDT CHAR(10)
--8. XÓA CỘT
ALTER TABLE NHACUNGCAP1
	DROP COLUMN SDT
--9. XÓA TABLE
DROP TABLE NhaCungCap1
--10. TẠO CÁC RANG BUỘC
--TẠO RÀNG BUỘC KHÓA CHÍNH
ALTER TABLE SANPHAM
	ADD PRIMARY KEY(MASP) --Cannot define PRIMARY KEY constraint on nullable column in table 'SANPHAM'.
ALTER TABLE SANPHAM
	ALTER COLUMN MASP CHAR(5) NOT NULL
ALTER TABLE SANPHAM
	ADD PRIMARY KEY(MASP) 
--CACH 2
CREATE TABLE Sanpham1 
( Masp CHAR(5) NOT NULL, 
  Tensp NVARCHAR(15), Dvt NVARCHAR(10), Dongia SMALLMONEY, SlTon INT ) 
ALTER TABLE SANPHAM1
	ADD CONSTRAINT PK_MASP PRIMARY KEY(MASP) 
--TẠO CỘT MANCC
ALTER TABLE SANPHAM
	ADD MANC INT
--11. TẠO RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE SANPHAM
	ADD FOREIGN KEY(MANC) REFERENCES NHACUNGCAP(MANCC)
--CÁCH 2
ALTER TABLE SANPHAM1 ADD MANCC INT
ALTER TABLE SANPHAM1
	ADD CONSTRAINT FK_MANCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP1(MANCC)
--12. QUI ĐỊNH ĐIỀU KIỆN RÀNG BUỘC KHI NHẬP DỮ LIỆU
ALTER TABLE SANPHAM
	ADD CONSTRAINT CK_SLTON CHECK(SLTON>=0 AND SLTON<=500)
--HOẶC 
ALTER TABLE SANPHAM
	ADD CONSTRAINT CK_SLTON CHECK(SLTON BETWEEN 0 AND 500)
ALTER TABLE SANPHAM
	ADD CONSTRAINT CK_DVT CHECK( DVT='KG' OR DVT =N'TẤN' OR DVT =N'TẠ' OR DVT='YEN')
--HOẶC
ALTER TABLE SANPHAM
	ADD CONSTRAINT CK_DVT CHECK(DVT IN ('KG','TA','YEN','TAN'))
--CÁCH 3
CREATE RULE DG AS @DG >=0
--ÁP DỤNG
sp_bindrule DG, 'SANPHAM.DONGIA'
--GỠ BỎ
SP_UNBINDRULE 'SANPHAM.DONGIA'
--XOA RANG BUOC
ALTER TABLE TENBANG DROP CONSTRAINT TENRANGBUOC
--13. QUI ĐỊNH RÀNG BUỘC GIÁ TRỊ BAN ĐẦU
ALTER TABLE SANPHAM
	ADD CONSTRAINT DF_DONGIA DEFAULT 500 FOR DONGIA
--XÓA RÀNG BUỘC DEFAULT
DROP DEFAULT DF_DONGIA
--HOẶC 
ALTER TABLE SANPHAM
	DROP CONSTRAINT DF_DONGIA
--14. XÓA RÀNG BUỘC
ALTER TABLE SANPHAM
	DROP CONSTRAINT DF_DONGIA
--15. tạo KHÓA CHÍNH CHO CTHOADON
ALTER TABLE CTHOADON
	ADD PRIMARY KEY (SOHD,MAHANG)
--C3
ALTER TABLE SANPHAM ADD NGAYNHAP DATE
CREATE DEFAULT NGAYHH AS GETDATE()
sp_bindefault NGAYHH, 'SANPHAM.NGAYNHAP'
--GỠ BỎ
sp_unbindefault 'SANPHAM.NGAYNHAP'
--XÓA RÀNG BUỘC DEFAULT
DROP DEFAULT DF_DONGIA
--CACH 2
--1. TẠO CSDL
CREATE DATABASE QLBH1
ON PRIMARY
	(NAME ='QLBH1_DATA',
	FILENAME= 'T:\DL\QLBH1_DATA.MDF',
	SIZE=10,
	MAXSIZE =20,
	FILEGROWTH=1)
LOG ON
	(NAME ='QLBH1_LOG',
	FILENAME= 'T:\DL\QLBH1_LOG.LDF',
	SIZE=5,
	MAXSIZE =10,
	FILEGROWTH=1)
--SU DUNG CSDL
	USE QLBH1
--TẠO NHOM SAN PHAM
CREATE TABLE NHOMSANPHAM
	(MANHOM INT PRIMARY KEY, TENNHOM NVARCHAR(15))
--TAO NHA CUNG CAP
CREATE TABLE NHACUNGCAP
	(MANCC INT PRIMARY KEY, TENNCC NVARCHAR(40) NOT NULL)
--TAO SAN PHAM
CREATE TABLE SANPHAM
	(MASP INT PRIMARY KEY, TENSP NVARCHAR(40) NOT NULL, 
	MANCC INT REFERENCES NHACUNGCAP(MANCC),
	MOTA NVARCHAR(50),
	MANHOM INT REFERENCES NHOMSANPHAM(MANHOM), 
	DVT NVARCHAR(20),
	GIAGOC MONEY CHECK(GIAGOC >0),
	SLTON INT CHECK(SLTON>=0))
--TAO KH
CREATE TABLE KHACHHANG
	(MAKH CHAR(5) PRIMARY KEY, TENKH NVARCHAR(40) NOT NULL,
	LOAIKH NCHAR(3) CHECK(LOAIKH IN('VL','TV','VIP')), DIEMTL INT CHECK (DIEMTL>=0))
--TAO HD
CREATE TABLE HOADON
	(MAHD INT PRIMARY KEY, NGAYLAP DATETIME DEFAULT GETDATE(), 
	MAKH CHAR(5) REFERENCES KHACHHANG (MAKH))
--TAO CTHD
CREATE TABLE CTHD
	(MAHD INT NOT NULL REFERENCES HOADON(MAHD) ,
	MASP INT NOT NULL REFERENCES SANPHAM(MASP) , 
	SOLUONG INT CHECK(SOLUONG>0),
	DONGIA MONEY ,
	CHIETKHAU MONEY CHECK(CHIETKHAU>=0),
	PRIMARY KEY(MAHD,MASP))

----LUU Y : RANG BUOC KHOA CHINH , KHOA NGOA
--TRUONG HỢP 1: KHÔNG CHO SỬA, XÓA DỮ LIỆU BẢNG CHA NẾU CÓ DL QUAN HỆ TỒN TẠI TRONG BẢNG CON
CREATE TABLE LOP (MALOP CHAR(5) PRIMARY KEY, TENLOP NVARCHAR(50),SISO INT)
CREATE TABLE SV (MASV CHAR(10) PRIMARY KEY, HOTEN NVARCHAR(50), MALOP CHAR(5))
--THÊM RANG BUỘC KHÓA NGOẠI
ALTER TABLE SV 
	ADD CONSTRAINT FK_MALOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
--TRUONG HỢP 2:  SỬA, XÓA DỮ LIỆU BẢNG CHA NẾU THÌ DL QUAN HỆ TỒN TẠI TRONG BẢNG CON CŨNG SỬA VÀ XÓA LUÔN
CREATE TABLE LOP1 (MALOP CHAR(5) PRIMARY KEY, TENLOP NVARCHAR(50),SISO INT)
CREATE TABLE SV1 (MASV CHAR(10) PRIMARY KEY, HOTEN NVARCHAR(50), MALOP CHAR(5))
--THÊM RANG BUỘC KHÓA NGOẠI
ALTER TABLE SV1 
	ADD CONSTRAINT FK_MALOP1 FOREIGN KEY (MALOP) REFERENCES LOP1 (MALOP) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE
CREATE TABLE NV (MANV CHAR(5) PRIMARY KEY, TENNV NVARCHAR(40), MANQL CHAR(5) REFERENCES NV(MANV))
--
CREATE TABLE NV(MANV CHAR(5)PRIMARY KEY, HOTEN NVARCHAR(40), MAPB CHAR(5),
	MANT CHAR(5) REFERENCES NV(MANV))

CREATE TABLE PB(MAPB CHAR(5)PRIMARY KEY, TENPB NVARCHAR(30), 
	MATP CHAR(5) REFERENCES NV(MANV))

ALTER TABLE NV ADD CONSTRAINT FK_MAPB FOREIGN KEY(MAPB) REFERENCES PB (MAPB)
--
--1. NHAP DU LIEU
--NHOMSP
INSERT NHOMSANPHAM VALUES(1,N'ĐIỆN TỬ')
SELECT * FROM NHOMSANPHAM
INSERT NHOMSANPHAM VALUES(2,N'GIA DỤNG'),(3,N'DỤNG CỤ GIA ĐÌNH'),(4,N'CÁC MẶT HÀNG KHÁC') --LỖI
ALTER TABLE NHOMSANPHAM ALTER COLUMN TENNHOM NVARCHAR(40)
--NHACUNGCAP
INSERT NhaCungCap VALUES(1,N'CONG TY TNHH ABC')
--SAN PHAM
INSERT SANPHAM VALUES(1,N'MÁY TÍNH',1,N'MÁY SONY',1,N'CÁI',7000,100)
SELECT * FROM Sanpham
--KH
INSERT KHACHHANG(MAKH,TENKH,LOAIKH) VALUES ('KH1',N'NGUYỄN THU HẰNG','VL')
SELECT * FROM KHACHHANG
--
SET DATEFORMAT DMY
INSERT HOADON VALUES (1,'2/10/2023','KH1')
--
UPDATE CTHD
SET DONGIA =DONGIA+0.05*DONGIA
WHERE MASP =2

---
UPDATE SANPHAM
SET SLTON =SLTON +100
WHERE MASP =3 AND MANCC =1

--
DELETE FROM NHOMSANPHAM WHERE MANHOM =4
SELECT * FROM NHOMSANPHAM